// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use prod schema (PostgreSQL) for Prisma generate in production builds
export default defineConfig({
  schema: "prisma/schema.prod.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
