// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Use dev schema (SQLite) in development, prod schema (PostgreSQL) in production
const schemaPath = process.env.NODE_ENV === 'production' 
  ? "prisma/schema.prod.prisma" 
  : "prisma/schema.dev.prisma";

export default defineConfig({
  schema: schemaPath,
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
