'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useParams, useRouter } from 'next/navigation';
import { X, Copy, Share2, CheckCircle, Sparkles, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { getDreamById, DreamWithAnalysis, getCurrentUser, CurrentUserInfo, DreamAnalysisResult } from '@/app/actions';
import { PLANS } from '@/lib/constants';
import { DreamResult } from '@/components/DreamResult';

export default function AnalysisPage() {
  const params = useParams();
  const router = useRouter();
  const [dream, setDream] = useState<DreamWithAnalysis | null>(null);
  const [user, setUser] = useState<CurrentUserInfo>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(false);

  const dreamId = params.id as string;

  useEffect(() => {
    async function loadData() {
      const [dreamData, userData] = await Promise.all([
        getDreamById(dreamId),
        getCurrentUser()
      ]);
      setDream(dreamData);
      setUser(userData);
      setLoading(false);
    }
    loadData();
  }, [dreamId]);

  const handleCopy = async () => {
    if (!dream?.analysis) return;
    
    try {
      const analysisData = JSON.parse(dream.analysis);
      const text = `✨ 夢境解析報告 ✨

📝 夢境摘要：${analysisData.summary}

🌙 氛圍：${analysisData.vibe}

${analysisData.analysis ? `🔮 深度分析：${analysisData.analysis}

💡 建議：${analysisData.reflection}` : ''}

---
Generated by Dream Record`;

      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  const handleShare = async () => {
    if (!dream?.analysis) return;
    
    try {
      const analysisData = JSON.parse(dream.analysis);
      
      if (navigator.share) {
        await navigator.share({
          title: '我的夢境解析',
          text: `✨ 夢境摘要：${analysisData.summary}\n🌙 氛圍：${analysisData.vibe}`,
          url: window.location.href
        });
        setShareSuccess(true);
        setTimeout(() => setShareSuccess(false), 2000);
      } else {
        // Fallback to copy
        handleCopy();
      }
    } catch (err) {
      console.error('Share failed:', err);
    }
  };

  const handleClose = () => {
    router.push('/');
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          className="text-center"
        >
          <div className="w-16 h-16 mx-auto mb-4 relative">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
              className="absolute inset-0 rounded-full border-2 border-transparent border-t-[var(--accent)] border-r-[var(--accent2)]"
            />
            <Sparkles className="w-8 h-8 text-[var(--accent)] absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
          </div>
          <p className="text-[var(--muted)]">載入解析中...</p>
        </motion.div>
      </div>
    );
  }

  if (!dream || !dream.analysis) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center"
        >
          <p className="text-[var(--muted)] mb-4">找不到此夢境解析</p>
          <Link 
            href="/"
            className="inline-flex items-center gap-2 px-4 py-2 bg-[var(--surface)] border border-[var(--border)] rounded-xl hover:bg-white/5 transition-colors"
          >
            <ArrowLeft size={16} />
            返回首頁
          </Link>
        </motion.div>
      </div>
    );
  }

  let analysisData: DreamAnalysisResult;
  try {
    analysisData = JSON.parse(dream.analysis);
  } catch {
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <p className="text-[var(--muted)]">解析資料格式錯誤</p>
      </div>
    );
  }

  const isPaidUser = user?.plan === PLANS.DEEP;

  // Prepare data for DreamResult - handle hiding logic here
  const displayResult: DreamAnalysisResult = {
    ...analysisData,
    analysis: isPaidUser ? analysisData.analysis : null,
    reflection: isPaidUser ? analysisData.reflection : null,
  };

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Animated Background */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 0.5 }}
          transition={{ duration: 1 }}
          className="absolute top-1/4 left-1/4 w-96 h-96 bg-[var(--accent)]/20 rounded-full blur-[100px]"
        />
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 0.3 }}
          transition={{ duration: 1, delay: 0.3 }}
          className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-[var(--accent2)]/20 rounded-full blur-[100px]"
        />
        {/* Floating particles */}
        {[...Array(15)].map((_, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0 }}
            animate={{ 
              opacity: [0, 0.6, 0],
              y: [0, -150],
            }}
            transition={{
              duration: 4 + (i % 3),
              repeat: Infinity,
              delay: i * 0.3
            }}
            className="absolute w-1 h-1 rounded-full bg-white/50"
            style={{
              left: `${(i * 7) % 100}%`,
              top: `${50 + (i * 3) % 50}%`
            }}
          />
        ))}
      </div>

      {/* Main Content */}
      <div className="relative z-10 min-h-screen p-4 md:p-8">
        {/* Header Actions */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="fixed top-4 right-4 z-50 flex items-center gap-2"
        >
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleCopy}
            className="p-3 rounded-xl bg-[var(--surface)]/80 backdrop-blur-xl border border-[var(--border)] hover:bg-white/10 transition-colors"
            title="複製"
          >
            {copied ? <CheckCircle size={20} className="text-green-400" /> : <Copy size={20} />}
          </motion.button>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleShare}
            className="p-3 rounded-xl bg-[var(--surface)]/80 backdrop-blur-xl border border-[var(--border)] hover:bg-white/10 transition-colors"
            title="分享"
          >
            {shareSuccess ? <CheckCircle size={20} className="text-green-400" /> : <Share2 size={20} />}
          </motion.button>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleClose}
            className="p-3 rounded-xl bg-[var(--surface)]/80 backdrop-blur-xl border border-[var(--border)] hover:bg-white/10 transition-colors"
            title="關閉"
          >
            <X size={20} />
          </motion.button>
        </motion.div>

        {/* Analysis Card */}
        <div className="max-w-2xl mx-auto pt-16 md:pt-8">
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 30 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          >
            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="text-center mb-8"
            >
              <motion.h1
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5 }}
                className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-[var(--accent)] to-[var(--accent2)] bg-clip-text text-transparent mb-2"
              >
                夢境解析
              </motion.h1>
              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.6 }}
                className="text-[var(--muted)]"
              >
                {new Date(dream.createdAt).toLocaleDateString('zh-TW', {
                  year: 'numeric',
                  month: 'long',
                  day: 'numeric'
                })}
              </motion.p>
            </motion.div>

            {/* Dream Content */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="bg-[var(--surface)]/50 backdrop-blur-xl border border-[var(--border)] rounded-3xl p-6 mb-8"
            >
              <h3 className="text-sm font-medium text-[var(--muted)] mb-2 uppercase tracking-wider">原始夢境</h3>
              <p className="text-white/90 whitespace-pre-wrap leading-relaxed">{dream.content}</p>
            </motion.div>

            {/* New Dream Result Component */}
            <DreamResult result={displayResult} />

            {/* Back Button */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1 }}
              className="text-center mt-12 pb-8"
            >
              <Link
                href="/"
                className="inline-flex items-center gap-2 px-6 py-3 bg-[var(--surface)] border border-[var(--border)] rounded-xl hover:bg-white/5 transition-colors"
              >
                <ArrowLeft size={18} />
                返回首頁
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
